# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18f412a05e6f40ae2de10b299bb20ce4d6e0901f6b52463710f8d2abd6f39c820cfa9b0be235358df9bbebeb5d030c1a57bcd6de4d4c93154cf10dbdf09dc5f

test:
  secret_key_base: 786955ffe92dd2e0bd7fc44c192a2a96bd4ee0df88bc846ec4ce40406c9e499e1e43256969343fbd96344b7cf06d0da8916a829b8f05504bf4f72e5d042939d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
